// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Y8Tfx53oXiqwvcn6tQpjaK0U3bBodWc',
    appId: '1:329166541514:web:03a09deca3629c89515a33',
    messagingSenderId: '329166541514',
    projectId: 'soko-b97c0',
    authDomain: 'soko-b97c0.firebaseapp.com',
    storageBucket: 'soko-b97c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6Yg5L_HrvYMzcmj0kRkJDGZCle-LkEA',
    appId: '1:329166541514:android:fb3acb3d23637b52515a33',
    messagingSenderId: '329166541514',
    projectId: 'soko-b97c0',
    storageBucket: 'soko-b97c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq31Pa2q4_M_ZgPiHR09fLMsczupLhmxY',
    appId: '1:329166541514:ios:75ce3e38f1841644515a33',
    messagingSenderId: '329166541514',
    projectId: 'soko-b97c0',
    storageBucket: 'soko-b97c0.firebasestorage.app',
    iosBundleId: 'com.example.soko',
  );
}
